from __future__ import annotations

from typing import Any


# ---------------------------------------------------------------------------
# 取证知识域注册表 — 每条定义一种取证分析能力，而非某道特定题目
# 匹配基于"知识域关键词"，使系统能对同类型问题通用作答
# ---------------------------------------------------------------------------
FORENSIC_KNOWLEDGE_DOMAINS: list[dict[str, Any]] = [
    {
        "domain_id": "last_boot_time",
        "topic": "last_boot_time",
        "description": "系统最后一次开机/启动时间分析",
        "keywords": ["开机时间", "启动时间", "最后一次开机", "最后开机", "last boot", "boot time"],
        "artifact_groups": ["registry_system", "event_logs_system"],
        "answer_format": "datetime",
        "extraction_notes": [
            "优先取 SYSTEM hive 的关机/启动痕迹。",
            "再用 System.evtx 的 12/13/6005/6006/1074 做交叉验证。",
        ],
    },
    {
        "domain_id": "note_content_extraction",
        "topic": "backup_phone_number",
        "description": "从便签/备忘录等提取文本内容（如号码、地址等）",
        "keywords": ["便签", "备忘", "备忘录", "号码", "笔记", "sticky note", "备用机"],
        "artifact_groups": ["sticky_notes", "user_docs", "images_or_embedded_objects"],
        "answer_format": "phone_number",
        "extraction_notes": [
            "优先看便签/桌面备忘录类证据。",
            "如正文不可见，需要处理嵌入对象、截图或富文本残留。",
        ],
    },
    {
        "domain_id": "browser_credential",
        "topic": "browser_saved_password",
        "description": "浏览器保存的登录凭据/密码提取",
        "keywords": ["浏览器密码", "保存密码", "登录凭据", "browser password", "login data", "saved password"],
        "artifact_groups": ["browser_login_data", "browser_local_state"],
        "answer_format": "string",
        "extraction_notes": [
            "优先定位 Chrome/Chromium 的 Login Data 和 Local State。",
            "需要完整的密码解密链时，再补 DPAPI/主密钥处理。",
        ],
    },
    {
        "domain_id": "software_version_query",
        "topic": "wechat_version",
        "description": "查询已安装软件的版本号（微信、QQ 等常见软件）",
        "keywords": ["版本", "软件版本", "安装版本", "version", "微信版本", "wechat version", "软件信息"],
        "artifact_groups": ["installed_software", "wechat_install_dir", "registry_software"],
        "answer_format": "version",
        "extraction_notes": [
            "优先从已安装软件与安装目录版本信息回答。",
        ],
    },
    {
        "domain_id": "remote_access_detection",
        "topic": "remote_control_software",
        "description": "检测系统中已安装/使用过的远程控制软件",
        "keywords": ["远程控制", "远控软件", "远程桌面", "远程访问", "remote control", "remote access",
                     "todesk", "向日葵", "raylink", "爱思远", "teamviewer", "anydesk"],
        "artifact_groups": ["installed_software", "shortcuts", "program_files_scan"],
        "answer_format": "multi_select",
        "extraction_notes": [
            "优先从卸载信息、快捷方式、安装目录三条证据链交叉确认。",
        ],
    },
    {
        "domain_id": "application_log_file_identification",
        "topic": "sunlogin_log_filename",
        "description": "根据时间戳定位应用程序日志文件",
        "keywords": ["日志文件", "日志文件名", "log file", "日志", "向日葵日志", "应用日志"],
        "artifact_groups": ["sunlogin_logs"],
        "answer_format": "filename",
        "extraction_notes": [
            "先定位应用安装目录，再按时间戳过滤具体日志。",
        ],
    },
    {
        "domain_id": "remote_connection_ip_extraction",
        "topic": "sunlogin_remote_ip_port",
        "description": "从远程控制日志中提取公网 IP 和端口",
        "keywords": ["公网ip", "ip地址", "ip和端口", "远程ip", "remote ip", "端口", "ip:port", "连接地址"],
        "artifact_groups": ["sunlogin_logs"],
        "answer_format": "ip_port",
        "extraction_notes": [
            "与日志文件定位使用同一份日志，直接按时间戳精确定位。",
        ],
    },
    {
        "domain_id": "file_hash_lookup",
        "topic": "file_by_md5",
        "description": "通过文件哈希（MD5/SHA）反查文件名或路径",
        "keywords": ["md5", "sha1", "sha256", "hash", "哈希", "文件哈希", "file hash"],
        "artifact_groups": ["hash_inventory", "file_listing"],
        "answer_format": "filename",
        "extraction_notes": [
            "需要对目标范围建立文件哈希清单，支持按 MD5 反查。",
        ],
    },
    {
        "domain_id": "file_content_extraction",
        "topic": "mnemonic_first_word",
        "description": "从容器/文档中提取特定文本内容（助记词、密钥等）",
        "keywords": ["助记词", "mnemonic", "文件内容", "容器内容", "解压", "文档提取", "钱包"],
        "artifact_groups": ["target_file_export", "docx_or_zip_unpack"],
        "answer_format": "string",
        "extraction_notes": [
            "先定位目标文件，再导出并解析真实容器内容。",
        ],
    },
    {
        "domain_id": "recent_file_access",
        "topic": "recent_audio_filename",
        "description": "分析最近访问/打开过的文件（音频、文档等）",
        "keywords": ["最近访问", "最近打开", "最近使用", "recent", "最近文件", "音频文件", "最近曾访问"],
        "artifact_groups": ["recent_items", "jump_lists", "shellbags"],
        "answer_format": "filename",
        "extraction_notes": [
            "优先看 Recent / Jump List / RecentDocs 等最近访问证据。",
        ],
    },
    {
        "domain_id": "usb_device_history",
        "topic": "recent_usb_device",
        "description": "分析最近连接的 USB 设备记录",
        "keywords": ["usb设备", "usb", "移动存储", "u盘", "removable", "usb device", "最近usb"],
        "artifact_groups": ["registry_devices", "usbstor", "mounted_devices"],
        "answer_format": "single_select",
        "extraction_notes": [
            "优先以 USBSTOR、MountedDevices、WPDBUSENUM 回答。",
        ],
    },
    {
        "domain_id": "audio_transcription_analysis",
        "topic": "audio_content_analysis",
        "description": "音频内容转写与语义分析（人名、地点、数字等信息提取）",
        "keywords": ["音频", "录音", "语音", "audio", "音频内容", "转写", "语音分析"],
        "artifact_groups": ["audio_export", "audio_transcript"],
        "answer_format": "string",
        "extraction_notes": [
            "需要先定位音频文件，再做离线转写与语义问答。",
        ],
    },
    # -----------------------------------------------------------------------
    # 日志分析类知识域
    # -----------------------------------------------------------------------
    {
        "domain_id": "last_shutdown_time",
        "topic": "last_shutdown_time",
        "description": "系统最后一次关机/重启时间分析",
        "keywords": ["关机时间", "最后关机", "shutdown time", "最后一次关机", "重启时间", "last shutdown"],
        "artifact_groups": ["registry_system", "event_logs_system"],
        "answer_format": "datetime",
        "extraction_notes": [
            "SYSTEM hive 的 ControlSet\\Control\\Windows 的 ShutdownTime 值。",
            "或 System.evtx 中 Event ID 1074/6006/6008 等关机事件。",
        ],
    },
    {
        "domain_id": "user_logon_activity",
        "topic": "user_logon_activity",
        "description": "用户登录/注销活动分析（登录时间、方式、来源 IP 等）",
        "keywords": ["登录", "登录时间", "登录记录", "注销", "logon", "logoff", "用户登录",
                     "rdp登录", "远程登录", "登录失败", "login", "登录历史"],
        "artifact_groups": ["event_logs_security", "security_audit", "user_logon_history"],
        "answer_format": "string",
        "extraction_notes": [
            "Security.evtx: Event ID 4624(登录成功)、4625(登录失败)、4634/4647(注销)。",
            "关注 LogonType: 2=本地交互, 3=网络, 7=解锁, 10=RemoteInteractive(RDP)。",
            "对于 RDP 登录，TerminalServices-LocalSessionManager Event ID 21/23/25。",
        ],
    },
    {
        "domain_id": "service_installation",
        "topic": "service_installation",
        "description": "系统服务安装/变更记录分析",
        "keywords": ["服务安装", "新服务", "服务创建", "service install", "service created",
                     "驱动安装", "driver install"],
        "artifact_groups": ["event_logs_system", "event_logs_security"],
        "answer_format": "string",
        "extraction_notes": [
            "System.evtx: Event ID 7045(新服务安装)、7034(服务崩溃)。",
            "Security.evtx: Event ID 4697(服务安装—需审计策略启用)。",
        ],
    },
    {
        "domain_id": "account_management",
        "topic": "account_management",
        "description": "用户账户创建/修改/删除分析",
        "keywords": ["账户创建", "新用户", "用户创建", "账户管理", "密码修改", "account created",
                     "user created", "password change", "账户变更"],
        "artifact_groups": ["event_logs_security", "registry_sam", "security_audit"],
        "answer_format": "string",
        "extraction_notes": [
            "Security.evtx: Event ID 4720(创建)、4722(启用)、4723/4724(密码变更)、",
            "4725(禁用)、4726(删除)、4738(属性变更)、4732/4733(组成员变更)。",
        ],
    },
    {
        "domain_id": "application_error_analysis",
        "topic": "application_error_analysis",
        "description": "应用程序错误/崩溃日志分析",
        "keywords": ["应用崩溃", "程序错误", "application error", "app crash", "蓝屏",
                     "异常终止", "application crash", "程序崩溃", "bugcheck"],
        "artifact_groups": ["event_logs_application", "event_logs_system"],
        "answer_format": "string",
        "extraction_notes": [
            "Application.evtx: Event ID 1000(应用程序错误)、1001(WER 报告)、1002(挂起)。",
            "System.evtx: Event ID 1001(BugCheck/蓝屏)。",
        ],
    },
    {
        "domain_id": "generic_log_timeline",
        "topic": "generic_log_timeline",
        "description": "通用日志时间线分析 — 按关键词在任意日志中搜索和排序事件",
        "keywords": ["日志分析", "日志时间线", "log analysis", "log timeline", "事件分析",
                     "日志搜索", "时间线", "活动记录", "操作记录"],
        "artifact_groups": ["event_logs_system", "event_logs_security", "event_logs_application",
                           "application_logs"],
        "answer_format": "string",
        "extraction_notes": [
            "对所有可用日志导出进行全文搜索和时间排序。",
            "支持自定义关键词过滤。",
        ],
    },
    # -----------------------------------------------------------------------
    # 终端命令解析类知识域
    # -----------------------------------------------------------------------
    {
        "domain_id": "command_history_analysis",
        "topic": "command_history_analysis",
        "description": "终端命令历史分析 — PowerShell/CMD/Bash 执行历史提取",
        "keywords": ["命令历史", "执行命令", "command history", "powershell历史", "cmd历史",
                     "终端记录", "命令记录", "执行过的命令", "shell history", "consolehost",
                     "bash history", "命令行", "terminal history"],
        "artifact_groups": ["command_history", "powershell_history", "cmd_history", "bash_history"],
        "answer_format": "string",
        "extraction_notes": [
            "PowerShell: %APPDATA%\\Microsoft\\Windows\\PowerShell\\PSReadLine\\ConsoleHost_history.txt",
            "CMD: doskey /history 或注册表 CommandProcessor\\CompletionChar。",
            "WSL/Bash: ~/.bash_history 或 ~/.zsh_history。",
        ],
    },
    {
        "domain_id": "program_execution_history",
        "topic": "program_execution_history",
        "description": "程序执行痕迹分析 — Prefetch/Amcache/ShimCache/SRUM",
        "keywords": ["程序执行", "执行过", "运行过", "program execution", "prefetch", "预取",
                     "amcache", "shimcache", "appcompat", "执行痕迹", "程序运行记录",
                     "哪些程序", "运行记录", "执行记录"],
        "artifact_groups": ["process_execution", "prefetch", "amcache", "shimcache"],
        "answer_format": "string",
        "extraction_notes": [
            "Prefetch: C:\\Windows\\Prefetch\\*.pf — 程序名、执行次数、最后执行时间。",
            "Amcache: HKLM\\SOFTWARE\\Microsoft\\Amcache.hve — 完整路径、SHA1、安装时间。",
            "ShimCache: SYSTEM\\CurrentControlSet\\Control\\Session Manager\\AppCompatCache — 执行顺序。",
        ],
    },
    {
        "domain_id": "suspicious_command_detection",
        "topic": "suspicious_command_detection",
        "description": "可疑命令检测 — 从命令历史和日志中发现异常/恶意命令",
        "keywords": ["可疑命令", "恶意命令", "suspicious command", "异常命令", "攻击命令",
                     "提权", "privilege escalation", "lateral movement", "横向移动",
                     "数据窃取", "exfiltration", "恶意脚本"],
        "artifact_groups": ["command_history", "powershell_history", "event_logs_security",
                           "process_execution"],
        "answer_format": "string",
        "extraction_notes": [
            "PowerShell 日志: Event ID 4103/4104 (Script Block Logging)。",
            "Security.evtx: Event ID 4688 (新进程创建，需审计策略启用)。",
            "关注: Invoke-Expression, -EncodedCommand, certutil, bitsadmin, net user 等。",
        ],
    },
    {
        "domain_id": "powershell_script_analysis",
        "topic": "powershell_script_analysis",
        "description": "PowerShell 脚本执行分析 — Script Block/Module/Transcription 日志",
        "keywords": ["powershell脚本", "powershell日志", "powershell script", "脚本执行",
                     "script block", "4104", "4103", "powershell log", "invoke-expression",
                     "encodedcommand", "脚本分析"],
        "artifact_groups": ["powershell_history", "event_logs_security", "event_logs_application"],
        "answer_format": "string",
        "extraction_notes": [
            "Event ID 4104 (Script Block): 完整的 PowerShell 脚本块内容。",
            "Event ID 4103 (Module Logging): 模块级命令调用记录。",
            "Transcription Log: PowerShell 会话完整文本输出。",
        ],
    },
    # -----------------------------------------------------------------------
    # Windows 时间信息取证知识域
    # -----------------------------------------------------------------------
    {
        "domain_id": "timestamp_decode",
        "topic": "timestamp_decode",
        "description": "时间戳解码 — 将原始数值（FILETIME/Unix/FAT32/WebKit）解码为人类可读时间",
        "keywords": ["时间戳", "timestamp", "filetime", "解码", "decode", "dcode",
                     "十六进制时间", "hex time", "0x", "epoch", "unix时间"],
        "artifact_groups": ["registry_system", "registry_ntuser"],
        "answer_format": "datetime",
        "extraction_notes": [
            "Windows FILETIME: 64-bit, 100ns intervals since 1601-01-01 UTC。",
            "Unix Timestamp: 秒(32/64-bit)或毫秒 since 1970-01-01 UTC。",
            "FAT32: 32-bit (16-bit date + 16-bit time), 2秒精度, 通常本地时间。",
            "WebKit/Chrome: 微秒 since 1601-01-01 UTC。",
        ],
    },
    {
        "domain_id": "timezone_analysis",
        "topic": "timezone_analysis",
        "description": "系统时区分析 — 确定检材的时区设置和UTC偏移",
        "keywords": ["时区", "timezone", "utc", "cst", "偏移", "offset", "时间偏差",
                     "系统时区", "time zone", "时钟"],
        "artifact_groups": ["registry_system"],
        "answer_format": "string",
        "extraction_notes": [
            "SYSTEM\\CurrentControlSet\\Control\\TimeZoneInformation: 包含 Bias/ActiveTimeBias。",
            "Bias = UTC - 本地时间（分钟），中国标准时间 Bias = -480 (即 UTC+8)。",
            "注意区分 StandardBias 和 DaylightBias（夏令时偏移）。",
        ],
    },
    {
        "domain_id": "file_timestamp_analysis",
        "topic": "file_timestamp_analysis",
        "description": "文件时间戳取证分析 — CMA（Created/Modified/Accessed）三时间对比与异常检测",
        "keywords": ["文件时间", "创建时间", "修改时间", "访问时间", "cma", "created", "modified",
                     "accessed", "时间戳篡改", "timestomping", "文件时间异常", "mft时间",
                     "mace", "$standard_information", "$file_name"],
        "artifact_groups": ["file_listing", "registry_ntuser"],
        "answer_format": "string",
        "extraction_notes": [
            "NTFS MFT: $STANDARD_INFORMATION (可被篡改) vs $FILE_NAME (较难篡改) 对比。",
            "CMA 异常: Modified < Created 表示文件被复制, C==M==A 表示批量解压。",
            "FAT32: 只有 2秒精度，Created 精度为 10ms, Accessed 只有日期无时分秒。",
        ],
    },
    # -----------------------------------------------------------------------
    # Windows 时间线分析知识域
    # -----------------------------------------------------------------------
    {
        "domain_id": "windows_timeline_analysis",
        "topic": "windows_timeline_analysis",
        "description": "Windows Timeline (ActivitiesCache.db) 用户活动时间线分析",
        "keywords": ["timeline", "时间线", "activitiescache", "活动缓存", "activities",
                     "用户活动", "activity", "应用使用", "app usage", "剪贴板",
                     "clipboard", "connecteddevicesplatform", "user activity"],
        "artifact_groups": ["windows_timeline"],
        "answer_format": "string",
        "extraction_notes": [
            "ActivitiesCache.db 位于: ~\\AppData\\Local\\ConnectedDevicesPlatform\\L.<user>\\",
            "Activity 表: AppId(JSON), ActivityType(5=Open,6=InUse,16=Clipboard), StartTime, EndTime。",
            "时间戳为 Unix epoch (秒)。Payload 字段包含 displayText/description 等 JSON 数据。",
            "Windows 10 1803+ 引入，Windows 11 部分版本已弃用 Timeline UI 但数据库仍存在。",
        ],
    },
    # -----------------------------------------------------------------------
    # Windows 事件日志取证知识域
    # -----------------------------------------------------------------------
    {
        "domain_id": "user_profile_service_events",
        "topic": "user_profile_service_events",
        "description": "User Profile Service 事件分析 — 用户登录/注销全过程追踪 (EventID 1-5, 67)",
        "keywords": ["user profile service", "用户配置文件", "会话登录", "session logon",
                     "登录通知", "注销通知", "登录过程", "ntuser.dat", "usrclass.dat",
                     "配置文件加载", "profile load", "登录类型regular"],
        "artifact_groups": ["user_profile_service"],
        "answer_format": "string",
        "extraction_notes": [
            "User Profile Service 日志位于 Application 或 System 日志。",
            "EventID=1: 收到用户登录通知。EventID=2: 完成登录通知处理。",
            "EventID=3: 收到用户注销通知。EventID=4: 完成注销通知处理。",
            "EventID=5: 加载注册表文件 (ntuser.dat / UsrClass.dat)。",
            "EventID=67: 登录类型 (Regular/Temporary)。",
        ],
    },
    {
        "domain_id": "rdp_remote_access",
        "topic": "rdp_remote_access",
        "description": "远程桌面 (RDP/Terminal Services) 连接分析",
        "keywords": ["远程桌面", "rdp", "远程访问", "remote desktop", "terminal services",
                     "远程连接", "mstsc", "远程登录", "3389", "remoteconnectionmanager",
                     "localsessionmanager", "远程会话"],
        "artifact_groups": ["rdp_history"],
        "answer_format": "string",
        "extraction_notes": [
            "LocalSessionManager%4Operational.evtx: EventID=21(登录成功), 22(Shell启动), 23(注销), 24(断开), 25(重连)。",
            "RemoteConnectionManager%4Operational.evtx: EventID=1149(用户认证成功, 含源IP)。",
            "Security.evtx: EventID=4624 LogonType=10 为 RDP 登录。",
            "源 IP 可从 EventID=1149 或 4624 的 IpAddress 字段提取。",
        ],
    },
    {
        "domain_id": "pnp_device_events",
        "topic": "pnp_device_events",
        "description": "即插即用 (PnP) 设备事件分析 — USB/外接设备接入记录",
        "keywords": ["即插即用", "pnp", "plug and play", "usb插入", "设备接入", "设备安装",
                     "20001", "20003", "setupapi", "设备记录", "外接设备", "u盘插入",
                     "kernel-pnp", "userpnp", "8001", "8002"],
        "artifact_groups": ["pnp_device_history"],
        "answer_format": "string",
        "extraction_notes": [
            "System.evtx: EventID=20001(驱动安装成功), 20003(驱动加载)。",
            "Microsoft-Windows-Kernel-PnP%4Configuration.evtx: EventID=400(配置开始), 410(完成), 430(限制)。",
            "Microsoft-Windows-UserPnp%4DeviceInstall.evtx: EventID=8001(请求安装), 8002(安装结束)。",
            "SetupAPI 日志: Win7+: windows\\INF\\Setupapi.dev.log, WinXP: windows\\Setupapi.log。",
        ],
    },
    {
        "domain_id": "system_time_change",
        "topic": "system_time_change",
        "description": "系统时间修改事件分析 — 区分自动同步和人为修改",
        "keywords": ["系统时间修改", "时间修改", "时间变更", "time change", "4616",
                     "修改时间", "时间篡改", "时钟修改", "系统时钟", "ntp同步",
                     "时间同步", "w32time"],
        "artifact_groups": ["system_time_change"],
        "answer_format": "string",
        "extraction_notes": [
            "System.evtx: EventID=1 (内核时间报告, 来源: Microsoft-Windows-Kernel-General)。",
            "Security.evtx: EventID=4616 (系统时间已更改, 含使用者账户名)。",
            "区分自动同步 vs 手动修改: 检查使用者账户名 — LOCAL SERVICE/NETWORK SERVICE=自动同步, 用户账户=手动修改。",
            "W32Time 服务 (EventID=35/37): 时间同步状态变化。",
        ],
    },
    {
        "domain_id": "wlan_network_events",
        "topic": "wlan_network_events",
        "description": "无线网络 (WLAN/WiFi) 连接事件分析",
        "keywords": ["无线网络", "wifi", "wlan", "wifi连接", "无线连接", "wifi历史",
                     "ssid", "wlan-autoconfig", "networkprofile", "wifi登录",
                     "网络连接", "wireless", "wifi history"],
        "artifact_groups": ["wifi_history"],
        "answer_format": "string",
        "extraction_notes": [
            "Microsoft-Windows-WLAN-AutoConfig%4Operational.evtx: EventID=8001(连接尝试), 8002(连接成功), 8003(断开)。",
            "Microsoft-Windows-NetworkProfile%4Operational.evtx: EventID=10000(网络连接), 10001(网络断开)。",
            "SSID、BSSID、信号强度等信息可从事件详情中提取。",
            "工具 WiFiHistoryView (NirSoft) 可辅助分析。",
        ],
    },
    {
        "domain_id": "event_log_filter",
        "topic": "event_log_filter",
        "description": "事件日志过滤器 — 按 EventID/来源/时间范围/关键词灵活过滤事件",
        "keywords": ["事件过滤", "event filter", "过滤事件", "筛选事件", "eventvwr",
                     "事件查看器", "event viewer", "过滤日志", "查找事件", "搜索事件",
                     "eventid过滤"],
        "artifact_groups": ["event_logs_system", "event_logs_security", "event_logs_application",
                           "event_logs_terminal_services", "event_logs_pnp", "event_logs_wlan"],
        "answer_format": "string",
        "extraction_notes": [
            "支持按 EventID、来源(Provider)、时间范围、关键词组合过滤。",
            "事件文件路径 (Vista+): \\Windows\\System32\\winevt\\Logs\\",
            "Windows 内置查看器: eventvwr.exe。",
        ],
    },
    # -----------------------------------------------------------------------
    # 回收站取证知识域
    # -----------------------------------------------------------------------
    {
        "domain_id": "recycle_bin_analysis",
        "topic": "recycle_bin_analysis",
        "description": "回收站 ($Recycle.Bin) 文件分析 — 已删除文件恢复与时间线重建",
        "keywords": ["回收站", "recycle bin", "$recycle", "删除文件", "已删除", "deleted file",
                     "$i文件", "$r文件", "recycler", "info2", "回收站分析", "删除时间",
                     "恢复文件", "recover file", "删除记录", "废纸篓"],
        "artifact_groups": ["recycle_bin_analysis"],
        "answer_format": "string",
        "extraction_notes": [
            "$Recycle.Bin 位于每个卷的根目录: X:\\$Recycle.Bin\\{用户SID}\\",
            "$I 文件: 元数据文件 (删除时间 FILETIME + 原始文件大小 + 原始路径)。",
            "$R 文件: 实际被删除的文件内容 (与对应 $I 文件同名)。",
            "格式版本: v1=Vista/Win7/8 (路径固定520B), v2=Win10+ (路径可变长)。",
            "WinXP: C:\\RECYCLER\\{SID}\\INFO2 二进制格式 (800字节记录)。",
            "SID 可用于关联删除操作到具体用户帐户。",
        ],
    },
    # -----------------------------------------------------------------------
    # 操作系统基本信息知识域
    # -----------------------------------------------------------------------
    {
        "domain_id": "os_basic_info",
        "topic": "os_basic_info",
        "description": "操作系统基本信息 — 计算机名、OS版本、安装时间、注册用户名、产品密钥",
        "keywords": ["计算机名", "computer name", "hostname", "操作系统", "os版本",
                     "系统版本", "windows版本", "安装时间", "install date", "注册用户",
                     "registered owner", "产品密钥", "product key", "product id",
                     "系统信息", "systeminfo", "os info", "操作系统版本",
                     "currentversion", "windows 10", "windows 11", "build number",
                     "系统安装时间", "安装日期"],
        "artifact_groups": ["registry_system", "installed_software"],
        "answer_format": "string",
        "extraction_notes": [
            "注册表路径: HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion",
            "ProductName = OS名称, CurrentBuildNumber = 构建号, InstallDate = 安装时间(Unix)",
            "RegisteredOwner = 注册用户名, ProductId = 产品ID。",
            "计算机名: HKLM\\SYSTEM\\CurrentControlSet\\Control\\ComputerName\\ComputerName",
            "产品密钥: 需从 DigitalProductId 二进制值解码。",
        ],
    },
    {
        "domain_id": "user_account_list",
        "topic": "user_account_list",
        "description": "系统用户账户列表 — 用户名、SID、创建时间、最后登录、账户类型",
        "keywords": ["用户列表", "用户账户", "user account", "用户名", "user list",
                     "sid", "管理员", "administrator", "guest", "账户信息",
                     "本地用户", "local user", "用户创建", "创建了几个用户",
                     "有哪些用户", "sam", "账户类型"],
        "artifact_groups": ["registry_sam", "user_logon_history"],
        "answer_format": "string",
        "extraction_notes": [
            "SAM 注册表: HKLM\\SAM\\SAM\\Domains\\Account\\Users",
            "每个用户子键名为 RID (如 000001F4=500=Administrator)。",
            "V 值含用户名偏移/长度、组成员资格等。F 值含最后登录时间(FILETIME)。",
            "常见 RID: 500=Administrator, 501=Guest, 1000+=普通用户。",
            "也可从 Security 日志 EventID=4720(创建) / 4726(删除) 获取。",
        ],
    },
    {
        "domain_id": "network_config",
        "topic": "network_config",
        "description": "系统网络配置 — IP地址、MAC地址、DNS、网关",
        "keywords": ["ip地址", "ip address", "mac地址", "mac address", "dns",
                     "网关", "gateway", "网络配置", "network config", "网卡",
                     "adapter", "dhcp", "子网掩码", "subnet mask", "ipv4",
                     "网络接口", "interface"],
        "artifact_groups": ["registry_system"],
        "answer_format": "string",
        "extraction_notes": [
            "注册表路径: HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\\{GUID}",
            "IPAddress, SubnetMask, DefaultGateway, NameServer(DNS)。",
            "DhcpIPAddress = DHCP 分配 IP, EnableDHCP = 1 表示 DHCP 启用。",
            "网卡信息: HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\NetworkCards",
        ],
    },
    {
        "domain_id": "lnk_shortcut_analysis",
        "topic": "lnk_shortcut_analysis",
        "description": "LNK 快捷方式文件解析 — 目标路径、MAC时间戳、卷序列号",
        "keywords": ["lnk", "快捷方式", "shortcut", ".lnk", "shell link",
                     "目标路径", "target path", "卷序列号", "volume serial",
                     "最近文档", "recent", "快捷文件"],
        "artifact_groups": ["lnk_shortcut_analysis"],
        "answer_format": "string",
        "extraction_notes": [
            ".lnk 文件为 MS Shell Link Binary Format (MS-SHLLINK)。",
            "Header (76B): Magic(4C000000), LinkFlags, FileAttributes, CreationTime/AccessTime/WriteTime(FILETIME)。",
            "LinkInfo 段: VolumeSerialNumber(4B), LocalBasePath — 用于确定目标磁盘。",
            "StringData 段: RelativePath, WorkingDir, Arguments — 用于确定目标路径。",
            "常见位置: Recent 文件夹、桌面、开始菜单。",
        ],
    },
    {
        "domain_id": "jump_list_analysis",
        "topic": "jump_list_analysis",
        "description": "JumpList 跳转列表分析 — 应用程序最近打开文件和固定项",
        "keywords": ["jumplist", "跳转列表", "jump list", "自动目标", "automatic destinations",
                     "custom destinations", "最近打开", "最近使用", "recent files",
                     "应用历史", "app history", "固定项", "pinned"],
        "artifact_groups": ["jump_list_analysis"],
        "answer_format": "string",
        "extraction_notes": [
            "AutomaticDestinations-ms: OLE 复合文档, 每个 numbered stream 是一个 LNK 文件 + DestList 元数据流。",
            "CustomDestinations-ms: 多个 LNK 按 magic(4C000000) 拼接。",
            "路径: %APPDATA%\\Microsoft\\Windows\\Recent\\AutomaticDestinations\\ 和 CustomDestinations\\",
            "文件名中的 AppID (16位HEX) 可通过 Jump List Names.txt 映射到应用程序名称。",
            "DestList 流包含: MRU 顺序、访问次数、最后访问时间、NetBIOS 名、流编号等。",
            "Win10+: DestList 条目为 130B+, Win7/8: 114B+。",
        ],
    },
    {
        "domain_id": "recent_docs_analysis",
        "topic": "recent_docs_analysis",
        "description": "注册表 RecentDocs MRU — 最近访问/打开的文件记录",
        "keywords": ["recentdocs", "最近文档", "最近访问", "最近打开", "recent docs",
                     "recently opened", "最近使用", "mru", "most recently used",
                     "ntuser", "最近文件", "打开历史"],
        "artifact_groups": ["recent_items"],
        "answer_format": "string",
        "extraction_notes": [
            "注册表路径: NTUSER.DAT\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RecentDocs",
            "子键按文件扩展名分类: .docx, .xlsx, .pdf, .txt 等。",
            "MRUListEx 值记录访问顺序 (最近在前)。每个编号值包含文件名 (UTF-16LE + 额外数据)。",
            "Recent 文件夹 (shell:recent) 包含对应的 LNK 快捷方式。",
        ],
    },
    {
        "domain_id": "user_assist_analysis",
        "topic": "user_assist_analysis",
        "description": "注册表 UserAssist — 用户执行程序的次数和最后运行时间 (ROT13 编码键名)",
        "keywords": ["userassist", "user assist", "程序执行", "运行次数", "执行次数",
                     "run count", "execution count", "rot13", "程序启动",
                     "launched", "app usage", "应用使用", "程序使用频率"],
        "artifact_groups": ["registry_ntuser"],
        "answer_format": "string",
        "extraction_notes": [
            "注册表路径: NTUSER.DAT\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\UserAssist\\{GUID}\\Count",
            "键名使用 ROT13 编码, 需解码才能看到真实程序路径。",
            "常见 GUID: {CEBFF5CD-ACE2-4F4F-9178-9926F41749EA} (可执行文件), {F4E57C4B-2036-45F0-A9AB-443BCFE33D9F} (快捷方式)。",
            "值数据 (Win7+): 前 4 字节=session, 偏移4=运行次数(4B), 偏移8=焦点次数(4B), 偏移12=焦点时间(4B), 偏移60=最后运行时间(FILETIME 8B)。",
        ],
    },
    {
        "domain_id": "srum_analysis",
        "topic": "srum_analysis",
        "description": "SRUM (System Resource Usage Monitor) — 应用使用时长、网络流量、CPU/内存统计",
        "keywords": ["srum", "srudb", "网络流量", "network usage", "应用使用时长",
                     "app usage", "resource usage", "资源使用", "data usage", "流量统计",
                     "bytes sent", "bytes received"],
        "artifact_groups": ["srum"],
        "answer_format": "string",
        "extraction_notes": [
            "数据库路径: C:\\Windows\\System32\\sru\\SRUDB.dat (ESE/Extensible Storage Engine)。",
            "关键表: {D10CA2FE-6FCF-4F6D-848E-B2E99266FA89} (应用网络流量),",
            "  {DA73FB89-2BEA-4DDC-86B8-6E048C6DA477} (CPU/内存), {FEE4E14F-02A9-4550-B5CE-5FA2DA202E37} (网络连接)。",
            "XWF 导出后通常为 CSV/TSV 格式。",
        ],
    },
    {
        "domain_id": "prefetch_deep_analysis",
        "topic": "prefetch_deep_analysis",
        "description": "Prefetch 深度解析 — 执行次数、上次运行时间、关联 DLL 列表",
        "keywords": ["prefetch", "pf", "预读取", "启动次数", "run count", "last run",
                     "上次运行", "dll", "加载的dll", "loaded dll"],
        "artifact_groups": ["prefetch"],
        "answer_format": "string",
        "extraction_notes": [
            "路径: C:\\Windows\\Prefetch\\*.pf",
            "Win8+: 最多记录 8 次最近运行时间; Win7: 仅 1 次。",
            "每个 .pf 文件包含程序名、执行次数、关联文件/DLL 列表。",
        ],
    },
    {
        "domain_id": "shellbags_analysis",
        "topic": "shellbags_analysis",
        "description": "ShellBags — 文件夹浏览历史 (包括已删除文件夹)",
        "keywords": ["shellbags", "shell bags", "文件夹历史", "浏览历史", "folder history",
                     "bagmru", "bags", "usrclass", "已删除文件夹", "folder access"],
        "artifact_groups": ["shellbags"],
        "answer_format": "string",
        "extraction_notes": [
            "注册表路径: NTUSER.DAT\\Software\\Microsoft\\Windows\\Shell\\BagMRU + Bags",
            "  和 UsrClass.dat\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\BagMRU + Bags。",
            "ShellBags 记录用户浏览过的文件夹路径、窗口位置、视图设置。",
            "即使文件夹已删除或USB已拔除，ShellBags 仍保留记录。",
        ],
    },
    {
        "domain_id": "file_signature_analysis",
        "topic": "file_signature_analysis",
        "description": "文件签名/Magic Bytes 分析 — 检测扩展名与实际文件类型不匹配",
        "keywords": ["magic bytes", "文件签名", "file signature", "文件头", "file header",
                     "伪装文件", "disguised", "隐藏文件", "mismatch", "扩展名不匹配"],
        "artifact_groups": ["file_listing"],
        "answer_format": "string",
        "extraction_notes": [
            "X-Ways 的 ‘Verify file type’ 功能可检测扩展名与实际类型不匹配。",
            "导出的 file_listing 中可能包含 type/category/signature 字段。",
            "常见伪装: .jpg 实际是 .exe, .doc 实际是 .rar 等。",
        ],
    },
    {
        "domain_id": "pcap_file_locator",
        "topic": "pcap_file_locator",
        "description": "流量包定位 — 查找 .pcap/.pcapng/.cap 文件",
        "keywords": ["pcap", "pcapng", "cap", "流量包", "网络抓包", "packet capture",
                     "wireshark", "拓包", "network capture"],
        "artifact_groups": ["file_listing"],
        "answer_format": "string",
        "extraction_notes": [
            "在 file_listing 中搜索 .pcap/.pcapng/.cap 扩展名。",
            "返回文件路径、大小、时间戳。",
        ],
    },
    {
        "domain_id": "bitlocker_veracrypt_detection",
        "topic": "bitlocker_veracrypt_detection",
        "description": "BitLocker/VeraCrypt 加密卷检测 — 识别加密卷类型、恢复密钥位置",
        "keywords": ["bitlocker", "veracrypt", "加密卷", "encrypted volume", "恢复密钥",
                     "recovery key", "fve", "full volume encryption", "truecrypt",
                     "加密磁盘", "加密分区", "bek", "bde"],
        "artifact_groups": ["encrypted_files", "file_listing", "registry_system"],
        "answer_format": "string",
        "extraction_notes": [
            "encrypted_files 导出包含 X-Ways 检测到的加密候选文件。",
            "file_listing 中搜索 .bek / BitLocker Recovery Key / VeraCrypt 容器文件。",
            "SYSTEM 注册表 FVE (Full Volume Encryption) 键包含 BitLocker 卷信息。",
            "常见 VeraCrypt 容器无固定扩展名，靠文件头 entropy 检测。",
        ],
    },
    {
        "domain_id": "scheduled_task_analysis",
        "topic": "scheduled_task_analysis",
        "description": "计划任务分析 — at/schtasks/Task Scheduler XML 解析",
        "keywords": ["计划任务", "scheduled task", "schtasks", "task scheduler",
                     "at command", "定时任务", "cron job", "任务计划",
                     "TaskCache", "task xml"],
        "artifact_groups": ["scheduled_tasks", "event_logs_security"],
        "answer_format": "string",
        "extraction_notes": [
            "计划任务 XML 文件路径: C:\\Windows\\System32\\Tasks\\",
            "注册表: SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache",
            "事件日志: Security.evtx 4698(创建)/4699(删除)/4702(修改)",
            "重点关注: 可执行路径、运行账户、触发条件、创建时间。",
        ],
    },
    {
        "domain_id": "autostart_service_analysis",
        "topic": "autostart_service_analysis",
        "description": "服务/自启动项详细分析 — Run/RunOnce/Services 注册表键深度解析",
        "keywords": ["自启动", "autostart", "autorun", "run key", "runonce",
                     "services", "服务", "启动项", "开机启动", "startup",
                     "image path", "imagepath", "boot execute"],
        "artifact_groups": ["registry_system", "registry_ntuser", "installed_software"],
        "answer_format": "string",
        "extraction_notes": [
            "NTUSER: Software\\Microsoft\\Windows\\CurrentVersion\\Run + RunOnce",
            "SYSTEM: ControlSet001\\Services (ImagePath, Start 类型)",
            "SOFTWARE: Microsoft\\Windows\\CurrentVersion\\Run + RunOnce",
            "Start 类型: 0=Boot, 1=System, 2=Automatic, 3=Manual, 4=Disabled",
            "重点: 非标准路径的服务、临时目录中的可执行文件。",
        ],
    },
    {
        "domain_id": "defender_antivirus_log",
        "topic": "defender_antivirus_log",
        "description": "Windows Defender/杀毒软件日志 — 检测/隔离/扫描记录",
        "keywords": ["defender", "杀毒", "antivirus", "malware detection",
                     "quarantine", "隔离", "威胁检测", "threat", "病毒",
                     "windows defender", "恶意软件", "mplog", "实时保护"],
        "artifact_groups": ["event_logs_defender", "event_logs_application"],
        "answer_format": "string",
        "extraction_notes": [
            "Windows-Defender/Operational 事件日志:",
            "  1116=检测到威胁, 1117=采取操作, 1006/1007=恶意软件扫描结果",
            "  5001=实时保护禁用, 5010/5012=扫描相关",
            "MPLog 文件: ProgramData\\Microsoft\\Windows Defender\\Support\\MPLog-*",
            "隔离区: ProgramData\\Microsoft\\Windows Defender\\Quarantine\\",
        ],
    },
    {
        "domain_id": "clipboard_history_analysis",
        "topic": "clipboard_history_analysis",
        "description": "剪贴板历史分析 — Win10+ 剪贴板历史 (ActivitiesCache ActivityType=16)",
        "keywords": ["剪贴板", "clipboard", "clipboard history", "剪贴板历史",
                     "复制粘贴", "copy paste", "activities clipboard",
                     "activitytype 16", "cloud clipboard"],
        "artifact_groups": ["windows_timeline"],
        "answer_format": "string",
        "extraction_notes": [
            "ActivitiesCache.db 中 ActivityType=16 为剪贴板条目。",
            "ClipboardPayload 字段包含实际剪贴板内容(可能是 JSON 编码)。",
            "StartTime/EndTime 记录复制时间。",
            "AppId 字段记录来源应用。",
        ],
    },
    {
        "domain_id": "print_history",
        "topic": "print_history",
        "description": "打印记录分析 — PrintService 事件日志",
        "keywords": ["打印", "print", "printer", "打印机", "print job",
                     "打印记录", "打印历史", "printservice",
                     "print spooler", "spool"],
        "artifact_groups": ["event_logs_printservice", "event_logs_system"],
        "answer_format": "string",
        "extraction_notes": [
            "PrintService/Operational 事件日志:",
            "  307=打印任务完成 (含文档名、打印机名、页数、用户)",
            "  805=打印任务创建",
            "System.evtx: Print Spooler 服务启动/停止事件",
            "SPL/SHD 文件: Windows\\System32\\spool\\PRINTERS\\",
        ],
    },
    {
        "domain_id": "usn_journal_analysis",
        "topic": "usn_journal_analysis",
        "description": "USN Journal ($UsnJrnl:$J) 变更日志分析 — 文件创建/删除/重命名追踪",
        "keywords": ["usn journal", "usn", "$usnjrnl", "变更日志", "change journal",
                     "文件变更", "file changes", "usn record", "ntfs journal",
                     "文件删除记录", "重命名记录"],
        "artifact_groups": ["usn_journal", "file_listing"],
        "answer_format": "string",
        "extraction_notes": [
            "$UsnJrnl:$J 位于 NTFS 卷根目录 $Extend\\$UsnJrnl 的 $J 数据流。",
            "USN_RECORD_V2 结构: RecordLength(4) + MajorVersion(2) + MinorVersion(2) +",
            "  FileReferenceNumber(8) + ParentFileReferenceNumber(8) + Usn(8) +",
            "  TimeStamp(8, FILETIME) + Reason(4) + SourceInfo(4) + SecurityId(4) +",
            "  FileAttributes(4) + FileNameLength(2) + FileNameOffset(2) + FileName(变长UTF-16)",
            "Reason 标志: 0x100=文件创建, 0x200=文件删除, 0x2000=重命名(旧名), 0x2000=重命名(新名)",
        ],
    },
    {
        "domain_id": "mft_entry_analysis",
        "topic": "mft_entry_analysis",
        "description": "MFT Entry 原始解析 — $STANDARD_INFORMATION/$FILE_NAME/$DATA 属性分析",
        "keywords": ["mft", "$mft", "mft entry", "file record", "ntfs mft",
                     "standard information", "file name attribute", "data runs",
                     "mft时间", "驻留文件", "resident", "非驻留", "timestomping"],
        "artifact_groups": ["mft_export", "file_listing"],
        "answer_format": "string",
        "extraction_notes": [
            "MFT Entry 固定1024字节 (标准), 起始签名 'FILE'。",
            "Header: Signature(4) + UpdateSeqOffset(2) + UpdateSeqSize(2) +",
            "  $LogFileSequenceNumber(8) + SequenceNumber(2) + LinkCount(2) +",
            "  FirstAttrOffset(2) + Flags(2) + UsedSize(4) + AllocatedSize(4)",
            "Flags: 0x01=InUse, 0x02=Directory",
            "$STANDARD_INFORMATION (type 0x10): C/M/A/E 四个时间戳 (FILETIME)",
            "$FILE_NAME (type 0x30): C/M/A/E 时间戳 + 文件名 (内核维护, 不可直接修改)",
            "SI vs FN 时间不一致 = 可能存在 timestomping。",
            "$DATA (type 0x80): Resident flag + 数据/Data Runs",
        ],
    },
    {
        "domain_id": "sqlite_wal_recovery",
        "topic": "sqlite_wal_recovery",
        "description": "SQLite WAL 恢复 — 从 -wal 文件提取已删除/未提交记录",
        "keywords": ["sqlite wal", "wal recovery", "wal恢复", "sqlite删除恢复",
                     "wal file", "write ahead log", "已删除记录", "deleted records",
                     "freelist", "sqlite recovery", "数据库恢复"],
        "artifact_groups": ["sqlite_wal", "windows_timeline", "browser_history"],
        "answer_format": "string",
        "extraction_notes": [
            "SQLite WAL (-wal文件) 包含未checkpoint的页面修改。",
            "WAL 文件头: magic(4)=0x377f0682, version(4), pageSize(4), ...",
            "WAL Frame Header: pageNumber(4), commitSize(4), salt1(4), salt2(4), checksum(8)",
            "每个 frame 后紧跟完整页面数据, 可能包含已删除但未覆盖的记录。",
            "FreeList 页面: 已释放的 B-tree 页可能保留旧数据。",
            "常见目标: ActivitiesCache.db-wal, History-wal, places.sqlite-wal",
        ],
    },
    {
        "domain_id": "browser_download_cookie",
        "topic": "browser_download_cookie",
        "description": "浏览器 Cookie/下载记录分析",
        "keywords": ["cookie", "download", "下载记录", "下载历史",
                     "浏览器下载", "browser download", "chrome download",
                     "edge download", "firefox download", "cookies"],
        "artifact_groups": ["browser_history"],
        "answer_format": "string",
        "extraction_notes": [
            "Chrome/Edge: History SQLite → downloads 表 (target_path, start_time, url)",
            "  Cookies SQLite → cookies 表 (host_key, name, value, expires_utc)",
            "  时间格式: WebKit/Chrome timestamp (微秒 since 1601-01-01)",
            "Firefox: places.sqlite → moz_annos (下载), cookies.sqlite → moz_cookies",
            "下载路径可揭示用户行为和文件来源。",
        ],
    },
    {
        "domain_id": "etw_trace_analysis",
        "topic": "etw_trace_analysis",
        "description": "ETW Trace (.etl) 分析 — Event Tracing for Windows",
        "keywords": ["etw", "etl", "event tracing", "trace log", "etw trace",
                     "etl file", "wpr", "xperf", "windows performance",
                     "事件跟踪", "跟踪日志"],
        "artifact_groups": ["etw_traces", "file_listing"],
        "answer_format": "string",
        "extraction_notes": [
            "ETL 文件位置: C:\\Windows\\System32\\WDI\\, C:\\Windows\\Panther\\",
            "  以及 ProgramData\\Microsoft\\Diagnosis\\ETLLogs\\",
            "WiFi ETL: C:\\Windows\\System32\\LogFiles\\WMI\\Wifi.etl",
            "Boot trace: C:\\Windows\\System32\\WDI\\LogFiles\\BootPerfDiagLogger.etl",
            "可用 tracerpt.exe 或 xperf 解析为 CSV/XML。",
            "常见取证价值: 网络连接、驱动加载、进程创建等系统级事件。",
        ],
    },
    {
        "domain_id": "partition_table_analysis",
        "topic": "partition_table_analysis",
        "description": "磁盘分区表分析 — MBR/GPT/分区数/起始扇区/分区大小",
        "keywords": ["分区表", "partition table", "gpt", "mbr", "guid partition",
                     "主引导记录", "分区数", "分区数量", "起始扇区", "start sector",
                     "分区类型", "partition type", "分区大小", "分区偏移",
                     "efi系统分区", "esp", "msr", "恢复分区", "recovery partition"],
        "artifact_groups": ["disk_partition_info", "file_listing"],
        "answer_format": "string",
        "extraction_notes": [
            "XWF 案件属性 → 证据对象属性 → 分区信息。",
            "MBR: 偏移 0x1BE 起，4个 16B 分区条目; 0x55AA 签名。",
            "GPT: LBA1 GPT Header, LBA2-33 分区条目 (每条目 128B)。",
            "注意区分 主分区/扩展分区/逻辑分区 (MBR) 或 GPT 分区。",
            "扇区大小通常为 512B (传统) 或 4096B (4Kn/AF)。",
        ],
    },
    {
        "domain_id": "volume_filesystem_info",
        "topic": "volume_filesystem_info",
        "description": "卷/文件系统信息 — 文件系统类型/簇大小/卷标/卷序列号/容量",
        "keywords": ["文件系统", "file system", "ntfs", "fat32", "exfat", "ext4",
                     "簇大小", "cluster size", "分配单元", "卷标", "volume label",
                     "卷序列号", "volume serial", "可用空间", "已用空间",
                     "总容量", "格式化", "allocation unit"],
        "artifact_groups": ["volume_info", "disk_partition_info", "registry_system"],
        "answer_format": "string",
        "extraction_notes": [
            "NTFS BPB: 偏移 0x0B 扇区字节数, 0x0D 每簇扇区数, 0x48 $MFT 簇号。",
            "NTFS 卷序列号: 0x48 处 8B (与 dir /a 看到的不同)。",
            "FAT32 BPB: 0x0B SectorSize, 0x0D SectorsPerCluster, 0x43 VolumeSerialNumber。",
            "XWF 可直接读取文件系统属性: Properties → File System。",
            "注册表 MountedDevices 可提供卷 GUID 与盘符映射。",
        ],
    },
    {
        "domain_id": "usb_device_forensic_timeline",
        "topic": "usb_device_forensic_timeline",
        "description": "USB 设备取证时间线 — VID/PID/序列号/首次连接/最后连接/盘符",
        "keywords": ["usb时间线", "usb timeline", "vid", "pid", "首次连接",
                     "first connected", "最后连接", "last connected", "usb制造商",
                     "usb品牌", "usb型号", "usb序列号", "usb serial",
                     "设备盘符", "drive letter", "mountpoint", "setupapi"],
        "artifact_groups": ["registry_devices", "usbstor", "mounted_devices",
                           "setupapi_logs", "event_logs_pnp"],
        "answer_format": "string",
        "extraction_notes": [
            "SYSTEM\\CurrentControlSet\\Enum\\USBSTOR: 设备类型、序列号。",
            "SYSTEM\\CurrentControlSet\\Enum\\USB: VID_xxxx&PID_xxxx。",
            "SYSTEM\\MountedDevices: \\DosDevices\\X: → 设备签名/盘符映射。",
            "SOFTWARE\\Microsoft\\Windows Portable Devices: FriendlyName。",
            "SetupAPI.dev.log: 首次安装时间 (Section start)。",
            "事件日志 DriverFrameworks-UserMode (EventID 2003/2100): 连接/断开。",
            "注册表 USB 键下 Properties\\{83da..}\\0064: 首次安装时间戳。",
        ],
    },
    {
        "domain_id": "deleted_partition_detection",
        "topic": "deleted_partition_detection",
        "description": "已删除/隐藏分区检测 — 未分配空间中的分区残留",
        "keywords": ["已删除分区", "deleted partition", "隐藏分区", "hidden partition",
                     "未分配空间", "unallocated", "分区残留", "分区恢复",
                     "丢失分区", "lost partition", "空闲空间"],
        "artifact_groups": ["disk_partition_info", "file_listing"],
        "answer_format": "string",
        "extraction_notes": [
            "XWF 可扫描未分配空间并识别残留文件系统签名。",
            "NTFS: 在偏移 0x03 查找 'NTFS    ' 魔数。",
            "FAT32: 在偏移 0x52 查找 'FAT32   ' 标识。",
            "GPT 备份表在磁盘最后一个 LBA，可用于恢复被破坏的主 GPT。",
            "XWF: Specialist → Interpret Image File As Disk → 识别隐藏分区。",
            "注意对比当前分区表覆盖范围与磁盘总大小，差异即为可疑区域。",
        ],
    },
    {
        "domain_id": "evidence_source_metadata",
        "topic": "evidence_source_metadata",
        "description": "证据源/镜像元数据 — Hash/采集时间/原始大小/扇区数/工具信息",
        "keywords": ["镜像", "image", "证据源", "evidence source", "磁盘镜像",
                     "dd镜像", "e01", "原始大小", "扇区数", "total sectors",
                     "采集工具", "acquisition", "镜像md5", "镜像sha1",
                     "镜像hash", "制作时间", "镜像完整性"],
        "artifact_groups": ["evidence_metadata", "disk_partition_info"],
        "answer_format": "string",
        "extraction_notes": [
            "E01 格式: EnCase 证据文件，含 examiner、notes、acquisition date 等元数据。",
            "XWF: Case Properties → Evidence Objects 可查看源信息。",
            "dd/raw: 无内嵌元数据，依赖外部日志或 hash 文件。",
            "AD1 (FTK): 包含采集信息、hash、时间戳。",
            "镜像大小 ÷ 512 = 总扇区数 (假设 512B 扇区)。",
            "校验: 对比采集时与验证时的 hash 值确认完整性。",
        ],
    },
    {
        "domain_id": "storage_media_overview",
        "topic": "storage_media_overview",
        "description": "存储介质总览 — 磁盘型号/容量/分区布局/介质类型",
        "keywords": ["硬盘", "磁盘", "存储介质", "u盘容量", "硬盘型号",
                     "disk model", "硬盘容量", "硬盘大小", "磁盘信息",
                     "存储设备", "ssd", "hdd", "固态硬盘", "机械硬盘",
                     "介质类型", "磁盘概览", "tf卡", "sd卡", "存储卡"],
        "artifact_groups": ["evidence_metadata", "disk_partition_info",
                           "volume_info", "registry_devices"],
        "answer_format": "string",
        "extraction_notes": [
            "SYSTEM\\CurrentControlSet\\Enum\\IDE 或 SCSI: 硬盘型号与序列号。",
            "SYSTEM\\CurrentControlSet\\Services\\disk\\Enum: 当前磁盘设备。",
            "磁盘容量 = 总扇区数 × 扇区大小。",
            "XWF 证据对象属性直接显示磁盘品牌、容量、接口类型。",
            "注册表 DeviceClasses 可区分 USB/SATA/NVMe 接口类型。",
            "SSD 特征: 无寻道时间、TRIM 支持 (影响数据恢复可能性)。",
        ],
    },
    {
        "domain_id": "boot_sector_analysis",
        "topic": "boot_sector_analysis",
        "description": "引导扇区/VBR 详细解析 — 总扇区/隐藏扇区/MFT位置/FAT参数",
        "keywords": ["引导扇区", "boot sector", "vbr", "bpb", "总扇区数",
                     "total sectors", "隐藏扇区", "hidden sectors", "mft位置",
                     "mft cluster", "fat大小", "fat size", "保留扇区",
                     "reserved sectors", "每扇区字节", "bytes per sector",
                     "每簇扇区", "sectors per cluster", "oem标识"],
        "artifact_groups": ["disk_partition_info", "volume_info"],
        "answer_format": "string",
        "extraction_notes": [
            "NTFS VBR 结构: 偏移 0x00 跳转指令, 0x03 OEM ID ('NTFS    ')。",
            "  0x0B Bytes/Sector, 0x0D Sectors/Cluster, 0x28 Total Sectors。",
            "  0x30 $MFT Cluster Number, 0x38 $MFTMirr Cluster。",
            "FAT32 VBR: 0x0B Bytes/Sector, 0x0D Sectors/Cluster。",
            "  0x0E Reserved Sectors, 0x10 FAT Count, 0x20 Total Sectors (32-bit)。",
            "  0x24 Sectors/FAT, 0x43 Volume Serial Number。",
            "XWF: 选中分区 → View → Template → Boot Sector 模板。",
        ],
    },
    {
        "domain_id": "file_carving_analysis",
        "topic": "file_carving_analysis",
        "description": "文件雕刻/恢复分析 — 从未分配空间恢复的文件统计",
        "keywords": ["文件雕刻", "file carving", "数据恢复", "data recovery",
                     "文件恢复", "recover", "未分配空间恢复", "carved files",
                     "删除文件恢复", "文件头", "file header", "magic number",
                     "签名恢复", "orphan file"],
        "artifact_groups": ["file_listing", "file_signature_analysis"],
        "answer_format": "string",
        "extraction_notes": [
            "XWF: Specialist → Refine Volume Snapshot → 勾选 File header signature search。",
            "XWF 恢复的文件标记: 'Previously existing, possibly recoverable'。",
            "雕刻依据文件头签名: JPEG=FF D8 FF, PNG=89 50 4E 47, PDF=%PDF。",
            "XWF file_listing 中 Status 字段可标识: existing/deleted/carved。",
            "注意: 雕刻文件无原始文件名，通常以偏移或序号命名。",
        ],
    },
    {
        "domain_id": "disk_activity_timeline",
        "topic": "disk_activity_timeline",
        "description": "磁盘活动时间线 — 综合 USN/MFT/文件时间戳的操作时间线",
        "keywords": ["磁盘活动", "disk activity", "磁盘时间线", "文件操作时间线",
                     "文件创建时间", "文件修改时间", "文件访问时间",
                     "操作顺序", "时间线分析", "timeline analysis",
                     "最早文件", "最晚文件", "活动高峰"],
        "artifact_groups": ["usn_journal", "mft_export", "file_listing"],
        "answer_format": "string",
        "extraction_notes": [
            "MFT $SI 时间戳: Created, Modified, Accessed, Entry Modified。",
            "USN Journal: 按时间顺序记录所有文件变更操作。",
            "file_listing 的 Created/Modified/Accessed 时间戳可构建时间线。",
            "注意时区: XWF 默认使用 UTC，需要根据案件背景转换。",
            "高密度活动期可揭示关键操作时段 (如数据外泄、恶意行为)。",
        ],
    },
    {
        "domain_id": "encryption_key_recovery",
        "topic": "encryption_key_recovery",
        "description": "加密恢复密钥分析 — BitLocker恢复密钥/TPM/FVEK",
        "keywords": ["恢复密钥", "recovery key", "bitlocker密钥", "fvek",
                     "tpm", "恢复id", "recovery id", "密钥保护器",
                     "key protector", "数字密码", "numerical password",
                     "启动密钥", "startup key", "bek文件"],
        "artifact_groups": ["registry_system", "encrypted_files", "file_listing"],
        "answer_format": "string",
        "extraction_notes": [
            "BitLocker 恢复密钥格式: 6位×8组 数字 (如 123456-789012-...)。",
            "SYSTEM 注册表: HKLM\\SYSTEM\\CCS\\Control\\FVEStats。",
            "恢复密钥可存储于: AD、Microsoft 账户、USB (.BEK)、打印/文件。",
            "BEK 文件: BitLocker 启动密钥，通常在 USB 根目录。",
            "TPM + PIN 模式: 需要同时有 TPM 绑定和 PIN 才能解锁。",
            "XWF: Tools → Decrypt → 需提供恢复密钥或 FVEK。",
        ],
    },
    {
        "domain_id": "external_device_full_history",
        "topic": "external_device_full_history",
        "description": "外接设备完整历史 — 多源交叉的设备连接记录综合分析",
        "keywords": ["外接设备", "external device", "设备历史", "device history",
                     "所有usb", "全部设备", "设备清单", "连接历史",
                     "设备列表", "设备统计", "设备连接次数",
                     "移动硬盘", "外接硬盘", "移动设备"],
        "artifact_groups": ["registry_devices", "setupapi_logs", "event_logs_pnp",
                           "event_logs_system", "registry_system"],
        "answer_format": "string",
        "extraction_notes": [
            "多源交叉验证: 注册表 USBSTOR + SetupAPI + PnP 事件日志 + MountedDevices。",
            "SYSTEM\\CCS\\Enum\\USBSTOR: 设备类型/序列号 (持久保存)。",
            "SYSTEM\\CCS\\Enum\\USB: VID_xxxx&PID_xxxx (所有 USB 设备)。",
            "SOFTWARE\\Microsoft\\Windows Portable Devices\\Devices: FriendlyName。",
            "NTUSER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\MountPoints2: 用户挂载记录。",
            "综合分析可得出: 设备首次/最后接入、使用频率、关联用户。",
        ],
    },
    {
        "domain_id": "anti_forensics_detection",
        "topic": "anti_forensics_detection",
        "description": "反取证/数据擦除检测 — 擦除工具痕迹/异常时间戳/隐藏操作",
        "keywords": ["反取证", "anti-forensics", "数据擦除", "擦除工具", "wipe",
                     "eraser", "dban", "sdelete", "cipher /w", "时间戳篡改",
                     "timestomping", "隐藏文件", "痕迹清除", "日志清除",
                     "证据销毁", "安全删除", "secure delete"],
        "artifact_groups": ["prefetch", "amcache", "usn_journal", "file_listing",
                           "event_logs_system", "event_logs_security"],
        "answer_format": "string",
        "extraction_notes": [
            "擦除工具痕迹: Prefetch/Amcache 中的 Eraser.exe, sdelete.exe, BleachBit。",
            "USN Journal: 大量连续删除操作记录 (Reason=0x200)。",
            "事件日志清除: EventID 1102 (Security), 104 (System) — 日志被清除。",
            "Timestomping 检测: $SI 与 $FN 时间戳差异超过合理范围。",
            "隐藏操作: ADS 滥用、伪装扩展名、目录隐藏属性。",
            "XWF: 标记 'Deletion in progress' 的文件异常密集。",
        ],
    },
]


def normalize_offline_question_text(text: str) -> str:
    lowered = text.strip().lower()
    return (
        lowered.replace("“", '"')
        .replace("”", '"')
        .replace("（", "(")
        .replace("）", ")")
        .replace("：", ":")
        .replace("，", ",")
        .replace("？", "?")
        .replace("请分析", "")
        .replace("并回答", "")
        .strip()
    )


def match_knowledge_domain(question: str) -> dict[str, Any] | None:
    """将问题文本匹配到最相关的取证知识域。"""
    normalized = normalize_offline_question_text(question)
    best_entry: dict[str, Any] | None = None
    best_score = -1
    for entry in FORENSIC_KNOWLEDGE_DOMAINS:
        score = 0
        for keyword in entry["keywords"]:
            if keyword.lower() in normalized:
                score += len(keyword)
        if score > best_score:
            best_score = score
            best_entry = entry
    return best_entry if best_score > 0 else None


def build_offline_question_plan(question: str) -> dict[str, Any]:
    entry = match_knowledge_domain(question)
    if entry is None:
        return {
            "question": question,
            "matched": False,
            "status": "unmapped",
            "notes": ["当前离线题库还没有覆盖这道题。"],
            "ai_next_step": (
                "该问题暂无对应分析器。可尝试: "
                "1) 改用 get_string_search_matches 在原始数据中搜索关键词; "
                "2) 使用 get_volume_snapshot_summary 查看文件列表。"
            ),
        }
    return {
        "question": question,
        "matched": True,
        "status": "planned",
        "domain_id": entry["domain_id"],
        "topic": entry["topic"],
        "description": entry["description"],
        "artifact_groups": list(entry["artifact_groups"]),
        "answer_format": entry["answer_format"],
        "extraction_notes": list(entry["extraction_notes"]),
    }

